name: Laravel

on:
  push:
    branches: [ "new-features" ]
  pull_request:
    branches: [ "new-features" ]

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Ajustez selon votre projet
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, bcmath
          coverage: none
      
      - name: Validate composer.json
        run: composer validate --strict
      
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory Permissions
        if: runner.os != 'Windows'
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      
      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
